.pragma library

// Shared by the room timeline and the thread view, which draw the same rows.

// The core's markup, adjusted for the web-link setting.
//
// Every tag in this string was generated by core/src/markup.rs — the sender's
// characters are all escaped by the time it gets here — so its anchors have
// exactly one shape and a pattern over them is safe in a way a pattern over a
// message body would never be. With links switched off the target goes and the
// link's text stays, which is what the plain-text path did all along.
function renderFormatted(markup, clickableLinks) {
    if (clickableLinks) {
        return markup
    }
    return markup.replace(/<a href="[^"]*">/g, "").replace(/<\/a>/g, "")
}
