.pragma library

// Shared by the room timeline and the thread view, which draw the same rows.

// The core's markup, adjusted for the web-link setting.
//
// Every tag in this string was generated by core/src/markup.rs — the sender's
// characters are all escaped by the time it gets here — so its anchors have
// exactly one shape and a pattern over them is safe in a way a pattern over a
// message body would never be. With links switched off the target goes and the
// link's text stays, which is what the plain-text path did all along.
function renderFormatted(markup, clickableLinks) {
    if (clickableLinks) {
        return markup
    }
    // Anchors never nest - markup.rs refuses a nested one - so each opening tag
    // is closed before the next opens and a whole anchor can be matched at
    // once. A Matrix permalink keeps its target even here: it is answered
    // inside the app and never reaches a browser, which is what the setting is
    // about. Every other link loses the target and stays as its text.
    return markup.replace(/<a href="([^"]*)">([\s\S]*?)<\/a>/g,
                          function(anchor, href, text) {
        var internal = href.indexOf("matrix.to/#/") >= 0
                       || href.indexOf("matrix:") === 0
                       || href.indexOf("xmatic:") === 0
        return internal ? anchor : text
    })
}
