// xmatic — native Matrix client for Sailfish OS.
//
// The Qt side is deliberately thin: it owns the Silica UI and the list models,
// while all Matrix protocol work (sync, timeline, encryption) lives in the Rust
// core behind the C ABI in src/generated/xmatic_core.h.

#include <QDir>
#include <QGuiApplication>
#include <QQmlContext>
#include <QQuickView>
#include <QScopedPointer>
#include <QStandardPaths>
#include <QString>

#include <sailfishapp.h>

#include <sys/prctl.h>

#include "appearancesettings.h"
#include "instancelock.h"
#include "languagesettings.h"
#include "matrixbridge.h"
#include "secretskeeper.h"

// Generated by qmake from the spec's XMATIC_VERSION define; a plain qmake
// build gets "dev". A header rather than a define so a version-only change
// still triggers a recompile — a bare -D survived in a stale object file
// and the About page named the previous release.
#include "xmatic_version.h"

namespace {

// Everything the core persists — state store, crypto store, session — lives
// here. Under Sailjail this resolves below the organisation and application
// name declared in the desktop file, and the sandbox grants it without any
// extra permission.
QString ensureDirectory(QStandardPaths::StandardLocation location)
{
    const QString path = QStandardPaths::writableLocation(location);
    if (path.isEmpty()) {
        return QString();
    }
    QDir().mkpath(path);
    return path;
}

} // namespace

int main(int argc, char *argv[])
{
    // This process holds an access token, the crypto store's keys and — for
    // the password login — briefly a password. Non-dumpable means no core
    // dumps and no ptrace/`/proc/<pid>/mem` access by other processes of the
    // same user; only root can still look inside. The price is that a crash
    // leaves no core dump for debugging — the journal is the diagnostic tool
    // on the device anyway.
    prctl(PR_SET_DUMPABLE, 0);

    QScopedPointer<QGuiApplication> app(SailfishApp::application(argc, argv));

    const QString dataDirectory = ensureDirectory(QStandardPaths::AppDataLocation);
    if (dataDirectory.isEmpty()) {
        qWarning("xmatic: no writable data directory; the core cannot start");
    }
    // Before anything opens the store. The core runs its SQLite stores without
    // the SDK's cross-process lock, which only holds up while there is exactly
    // one process per store — and nothing on the system guarantees that (see
    // src/instancelock.cpp). A second start hands over to the running instance
    // and leaves; a share that arrived by D-Bus activation is delivered to that
    // instance by the bus once it owns the name, so nothing is dropped.
    if (!acquireInstanceLock(dataDirectory)) {
        qInfo("xmatic: another instance owns this store; handing over");
        raiseRunningInstance();
        return 0;
    }

    // Attachments go to the cache: they can always be downloaded again, and
    // the system may reclaim the space.
    const QString cacheDirectory = ensureDirectory(QStandardPaths::CacheLocation);

    // The store key from Sailfish Secrets encrypts the SQLite stores and the
    // session file. Empty when the secrets service is unavailable — the app
    // then runs as before, with unencrypted stores, and the keeper has said
    // so in the journal.
    QString storeKey = obtainStoreKey(dataDirectory);
    MatrixBridge bridge(dataDirectory, cacheDirectory, storeKey);
    if (!storeKey.isEmpty()) {
        storeKey.fill(QChar('0'));
    }
    qInfo("xmatic: %s", qPrintable(bridge.coreVersion()));

    AppearanceSettings appearance;

    LanguageSettings language;

    QScopedPointer<QQuickView> view(SailfishApp::createView());
    // After createView(): it installs libsailfishapp's device-locale translator,
    // and the one installed last is asked first.
    LanguageSettings::applyTo(app.data());

    view->rootContext()->setContextProperty(QStringLiteral("matrix"), &bridge);
    view->rootContext()->setContextProperty(QStringLiteral("appearance"), &appearance);
    view->rootContext()->setContextProperty(QStringLiteral("language"), &language);
    view->rootContext()->setContextProperty(QStringLiteral("appVersion"),
                                            QStringLiteral(XMATIC_VERSION_STRING));
    view->setSource(SailfishApp::pathTo(QStringLiteral("qml/harbour-xmatic.qml")));
    view->show();

    return app->exec();
}
