// xmatic - native Matrix client for Sailfish OS. The Qt side owns the UI and
// the models; all protocol work lives in the Rust core behind the C ABI.

#include <QDir>
#include <QEventLoop>
#include <QFile>
#include <QGuiApplication>
#include <QQmlContext>
#include <QQmlEngine>
#include <QQuickView>
#include <QScopedPointer>
#include <QStandardPaths>
#include <QString>
#include <QThread>
#include <QTimer>

#include <sailfishapp.h>

#include <sys/prctl.h>
#include <sys/stat.h>

#include "appearancesettings.h"
#include "appservice.h"
#include "appsettings.h"
#include "callengine.h"
#include "emojiimageprovider.h"
#include "emojiset.h"
#include "emojistore.h"
#include "instancelock.h"
#include "pushwake.h"
#include "voicedecode.h"
#include "languagesettings.h"
#include "readingpositions.h"
#include "matrixbridge.h"
#include "outgoingimage.h"
#include "secretskeeper.h"

// Generated by qmake from the spec's version. A header rather than a define:
// a bare -D survived in a stale object and the About page named the last release.
#include "xmatic_version.h"

namespace {

// Everything the core persists lives here. Under Sailjail this resolves below
// the names in the desktop file, and needs no extra permission.
QString ensureDirectory(QStandardPaths::StandardLocation location)
{
    const QString path = QStandardPaths::writableLocation(location);
    if (path.isEmpty()) {
        return QString();
    }
    QDir().mkpath(path);
    return path;
}

} // namespace

namespace {

/// A push wake-up holds the store for seconds and owns no window. Asked to
/// yield, it quits; the app waits for the lock instead of ending silently.
bool takeStoreFromWakeUp(const QString &dataDirectory)
{
    if (instanceIsRunning()) {
        return false;
    }
    QFile yield(dataDirectory + QStringLiteral("/") + QStringLiteral(XMATIC_WAKE_YIELD_FILE));
    if (!yield.open(QIODevice::WriteOnly)) {
        return false;
    }
    yield.close();
    for (int attempt = 0; attempt < 40; ++attempt) {
        QThread::msleep(100);
        if (acquireInstanceLock(dataDirectory)) {
            return true;
        }
    }
    QFile::remove(yield.fileName());
    return false;
}

} // namespace

int main(int argc, char *argv[])
{
    // Before any thread starts.
    pushPrelude(argv[0]);

    // The push-wake branch before Qt: that path must never put a window up. The
    // mode travels in the environment - SailJail matches argv exactly.
    if (qEnvironmentVariableIsSet(XMATIC_PUSH_WAKE_ENV)) {
        return runPushWake(argc, argv);
    }

    // No core dumps, no ptrace: this process holds the token and the crypto keys.
    prctl(PR_SET_DUMPABLE, 0);
    // 0600 on everything this process creates. `restrict_store` runs once, and
    // SQLite's -wal and -shm are written after it.
    umask(S_IRWXG | S_IRWXO);

    // One received voice message decoded, then gone: before Qt, before the
    // store, never the instance lock. See src/voicedecode.cpp.
    if (qEnvironmentVariableIsSet(XMATIC_VOICE_DECODE_ENV)) {
        return runVoiceDecode();
    }


    QScopedPointer<QGuiApplication> app(SailfishApp::application(argc, argv));

    // What the link handler's desktop file passes as its %u. Taken as it stands
    // and judged later: nothing here decides what it means, and nothing logs it
    // - a matrix.to link carries a room address, often a user id.
    QString startupLink;
    for (int i = 1; i < argc; i++) {
        const QString argument = QString::fromLocal8Bit(argv[i]);
        if (!argument.startsWith(QLatin1Char('-'))) {
            startupLink = argument;
            break;
        }
    }

    // Delivered, never opened here: this process has the handler's identity, and
    // Sailjail grants rights by identity - no app files, no store key.
    if (!startupLink.isEmpty()) {
        if (deliverLink(startupLink)) {
            return 0;
        }
        qWarning("xmatic: the link could not be delivered");
        return 1;
    }

    const QString dataDirectory = ensureDirectory(QStandardPaths::AppDataLocation);
    // Without it the store, the session and the swept cache all become
    // relative to the working directory. Nothing to fall back to.
    if (dataDirectory.isEmpty()) {
        qWarning("xmatic: no writable data directory; refusing to start");
        return 1;
    }
    // Before anything opens the store: the core runs SQLite without the SDK's
    // cross-process lock, and nothing else guarantees one process per store.
    if (!acquireInstanceLock(dataDirectory) && !takeStoreFromWakeUp(dataDirectory)) {
        qInfo("xmatic: another instance owns this store; handing over");
        raiseRunningInstance();
        return 0;
    }
    // Holding the store: a request to yield, ours or a leftover, is answered.
    QFile::remove(dataDirectory + QStringLiteral("/") + QStringLiteral(XMATIC_WAKE_YIELD_FILE));

    // Attachments go to the cache: they can always be downloaded again, and
    // the system may reclaim the space.
    const QString cacheDirectory = ensureDirectory(QStandardPaths::CacheLocation);
    if (cacheDirectory.isEmpty()) {
        qWarning("xmatic: no writable cache directory; refusing to start");
        return 1;
    }

    // Copies made for an upload cannot be dropped when it is handed over: the
    // upload runs on its own. Yesterday's are gone for sure.
    pruneOutgoingImages();

    // The store key's outcome, not just whether it worked: "install this package"
    // and "try again" are different advice. Logged unconditionally - it steers a user.
    qInfo("xmatic: secrets daemon reachable: %d", secretsDaemonPresent() ? 1 : 0);
    StoreKeyResult storeKey = obtainStoreKey(dataDirectory);
    if (storeKey.state != StoreKeyState::Available) {
        qWarning("xmatic: no store key (state %d, daemon installed: %d): %s",
                 static_cast<int>(storeKey.state),
                 secretsDaemonPresent() ? 1 : 0,
                 qPrintable(storeKey.errorMessage));
    }

    // Before the bridge: it reads a setting while opening a room and listens
    // for the one that has to rebuild a timeline.
    AppSettings settings;
    settings.dropRetiredKeys();

    // The app's D-Bus object: the notification's tap and the instance
    // hand-over reach the running app through it, and nothing else does.
    AppService service;
    service.publish();

    MatrixBridge bridge(dataDirectory, cacheDirectory, storeKey, &settings);
    bridge.setAnnouncePushes(true);
    bridge.closePushBanners();
    if (!storeKey.key.isEmpty()) {
        storeKey.key.fill(QChar('0'));
    }
    qInfo("xmatic: %s", qPrintable(bridge.coreVersion()));

    // The emoji picture set. Created before the view, because the view is handed
    // the provider.
    EmojiStore emojiStore(dataDirectory + QStringLiteral("/emoji"));
    EmojiSet emojiSet(&emojiStore);
    bridge.setEmojiStore(&emojiStore);

    AppearanceSettings appearance;

    LanguageSettings language;

    // Where the reader stood in each room. Memory only: it ends with the app,
    // the way the same feature does in other clients.
    ReadingPositions positions;

    QScopedPointer<QQuickView> view(SailfishApp::createView());
    // After createView(): it installs libsailfishapp's device-locale translator,
    // and the one installed last is asked first.
    LanguageSettings::applyTo(app.data());

    view->rootContext()->setContextProperty(QStringLiteral("matrix"), &bridge);
    view->rootContext()->setContextProperty(QStringLiteral("settings"), &settings);
    view->rootContext()->setContextProperty(QStringLiteral("activation"), &service);
    view->rootContext()->setContextProperty(QStringLiteral("appearance"), &appearance);
    view->rootContext()->setContextProperty(QStringLiteral("language"), &language);
    view->rootContext()->setContextProperty(QStringLiteral("emojiSet"), &emojiSet);
    view->rootContext()->setContextProperty(QStringLiteral("positions"), &positions);
    // A sign-out ends every room this knew about; the ids must not outlive it.
    QObject::connect(&bridge, &MatrixBridge::sessionChanged, &positions, [&bridge, &positions]() {
        if (bridge.sessionState() != QLatin1String("signed-in")) {
            positions.clear();
        }
    });
    // Takes ownership; the store outlives it, being on the stack of main().
    view->engine()->addImageProvider(QStringLiteral("xmatic-emoji"),
                                     new EmojiImageProvider(&emojiStore));
    view->rootContext()->setContextProperty(QStringLiteral("appVersion"),
                                            QStringLiteral(XMATIC_VERSION_STRING));
    // The wipe the privacy page offers, on the way out. A killed process never
    // gets here; the bridge therefore also clears leftovers at start.
    QObject::connect(app.data(), &QGuiApplication::aboutToQuit, &bridge, [&bridge, &settings]() {
        // A call left running would hold the other side in it until its watch gives
        // up. The core sends on its own threads; a second lets the hangup leave.
        auto *calls = qobject_cast<CallEngine *>(bridge.calls());
        if (calls && calls->state() != QLatin1String("idle")) {
            calls->hangUp();
            QEventLoop wait;
            QTimer::singleShot(1000, &wait, &QEventLoop::quit);
            wait.exec();
        }
        const QString when = settings.mediaWipe();
        if (when == QStringLiteral("exit") || when == QStringLiteral("background")) {
            bridge.clearMediaCache();
        }
    });

    // A notification tap works because lipstick activates the app, but a call
    // arriving while the app sits in the switcher has to raise its own window.
    QObject::connect(&service, &AppService::raiseRequested, view.data(), [&view]() {
        view->raise();
        view->requestActivate();
    });
    QObject::connect(&service, &AppService::notifiedRoomRequested, view.data(), [&view]() {
        view->raise();
        view->requestActivate();
    });

    view->setSource(SailfishApp::pathTo(QStringLiteral("qml/harbour-xmatic.qml")));
    view->show();

    return app->exec();
}
