// xmatic - native Matrix client for Sailfish OS. The Qt side owns the UI and
// the models; all protocol work lives in the Rust core behind the C ABI.

#include <QDir>
#include <QGuiApplication>
#include <QQmlContext>
#include <QQmlEngine>
#include <QQuickView>
#include <QScopedPointer>
#include <QStandardPaths>
#include <QString>

#include <sailfishapp.h>

#include <sys/prctl.h>
#include <sys/stat.h>

#include "appearancesettings.h"
#include "appservice.h"
#include "appsettings.h"
#include "emojiimageprovider.h"
#include "emojiset.h"
#include "emojistore.h"
#include "instancelock.h"
#include "pushwake.h"
#include "languagesettings.h"
#include "matrixbridge.h"
#include "secretskeeper.h"

// Generated by qmake from the spec's version. A header rather than a define:
// a bare -D survived in a stale object and the About page named the last release.
#include "xmatic_version.h"

namespace {

// Everything the core persists lives here. Under Sailjail this resolves below
// the names in the desktop file, and needs no extra permission.
QString ensureDirectory(QStandardPaths::StandardLocation location)
{
    const QString path = QStandardPaths::writableLocation(location);
    if (path.isEmpty()) {
        return QString();
    }
    QDir().mkpath(path);
    return path;
}

} // namespace

int main(int argc, char *argv[])
{
    // The push-wake branch before Qt: that path must never put a window up. The
    // mode travels in the environment - SailJail matches argv exactly.
    if (qEnvironmentVariableIsSet(XMATIC_PUSH_WAKE_ENV)) {
        return runPushWake(argc, argv);
    }

    // No core dumps, no ptrace: this process holds the token and the crypto keys.
    prctl(PR_SET_DUMPABLE, 0);
    // 0600 on everything this process creates. `restrict_store` runs once, and
    // SQLite's -wal and -shm are written after it.
    umask(S_IRWXG | S_IRWXO);

    QScopedPointer<QGuiApplication> app(SailfishApp::application(argc, argv));

    const QString dataDirectory = ensureDirectory(QStandardPaths::AppDataLocation);
    // Without it the store, the session and the swept cache all become
    // relative to the working directory. Nothing to fall back to.
    if (dataDirectory.isEmpty()) {
        qWarning("xmatic: no writable data directory; refusing to start");
        return 1;
    }
    // Before anything opens the store: the core runs SQLite without the SDK's
    // cross-process lock, and nothing else guarantees one process per store.
    if (!acquireInstanceLock(dataDirectory)) {
        qInfo("xmatic: another instance owns this store; handing over");
        raiseRunningInstance();
        return 0;
    }

    // Attachments go to the cache: they can always be downloaded again, and
    // the system may reclaim the space.
    const QString cacheDirectory = ensureDirectory(QStandardPaths::CacheLocation);
    if (cacheDirectory.isEmpty()) {
        qWarning("xmatic: no writable cache directory; refusing to start");
        return 1;
    }

    // The store key's outcome, not just whether it worked: "install this package"
    // and "try again" are different advice. Logged unconditionally - it steers a user.
    qInfo("xmatic: secrets daemon reachable: %d", secretsDaemonPresent() ? 1 : 0);
    StoreKeyResult storeKey = obtainStoreKey(dataDirectory);
    if (storeKey.state != StoreKeyState::Available) {
        qWarning("xmatic: no store key (state %d, daemon installed: %d): %s",
                 static_cast<int>(storeKey.state),
                 secretsDaemonPresent() ? 1 : 0,
                 qPrintable(storeKey.errorMessage));
    }

    // Before the bridge: it reads a setting while opening a room and listens
    // for the one that has to rebuild a timeline.
    AppSettings settings;
    settings.dropRetiredKeys();

    // The app's D-Bus object: the notification's tap and the instance
    // hand-over reach the running app through it, and nothing else does.
    AppService service;
    service.publish();

    MatrixBridge bridge(dataDirectory, cacheDirectory, storeKey, &settings);
    if (!storeKey.key.isEmpty()) {
        storeKey.key.fill(QChar('0'));
    }
    qInfo("xmatic: %s", qPrintable(bridge.coreVersion()));

    // The emoji picture set. Created before the view, because the view is handed
    // the provider.
    EmojiStore emojiStore(dataDirectory + QStringLiteral("/emoji"));
    EmojiSet emojiSet(&emojiStore);
    bridge.setEmojiStore(&emojiStore);

    AppearanceSettings appearance;

    LanguageSettings language;

    QScopedPointer<QQuickView> view(SailfishApp::createView());
    // After createView(): it installs libsailfishapp's device-locale translator,
    // and the one installed last is asked first.
    LanguageSettings::applyTo(app.data());

    view->rootContext()->setContextProperty(QStringLiteral("matrix"), &bridge);
    view->rootContext()->setContextProperty(QStringLiteral("settings"), &settings);
    view->rootContext()->setContextProperty(QStringLiteral("activation"), &service);
    view->rootContext()->setContextProperty(QStringLiteral("appearance"), &appearance);
    view->rootContext()->setContextProperty(QStringLiteral("language"), &language);
    view->rootContext()->setContextProperty(QStringLiteral("emojiSet"), &emojiSet);
    // Takes ownership; the store outlives it, being on the stack of main().
    view->engine()->addImageProvider(QStringLiteral("xmatic-emoji"),
                                     new EmojiImageProvider(&emojiStore));
    view->rootContext()->setContextProperty(QStringLiteral("appVersion"),
                                            QStringLiteral(XMATIC_VERSION_STRING));
    // The wipe the privacy page offers, on the way out. A killed process never
    // gets here; the bridge therefore also clears leftovers at start.
    QObject::connect(app.data(), &QGuiApplication::aboutToQuit, &bridge, [&bridge, &settings]() {
        const QString when = settings.mediaWipe();
        if (when == QStringLiteral("exit") || when == QStringLiteral("background")) {
            bridge.clearMediaCache();
        }
    });

    // A notification tap works because lipstick activates the app, but a call
    // arriving while the app sits in the switcher has to raise its own window.
    QObject::connect(&service, &AppService::raiseRequested, view.data(), [&view]() {
        view->raise();
        view->requestActivate();
    });
    QObject::connect(&service, &AppService::notifiedRoomRequested, view.data(), [&view]() {
        view->raise();
        view->requestActivate();
    });

    view->setSource(SailfishApp::pathTo(QStringLiteral("qml/harbour-xmatic.qml")));
    view->show();

    return app->exec();
}
